// Mock challenges data for demo
export const mockChallenges = [
  {
    id: 'challenge-1',
    title: 'Build a Real-Time Chat Application',
    description: 'Create a full-stack real-time chat application using WebSockets. Must include user authentication, message history, and typing indicators.',
    difficulty: 'Advanced',
    type: 'Full-Stack Development',
    prize: '$5,000',
    participants: 342,
    daysLeft: 8,
    requirements: [
      'Real-time messaging with WebSockets',
      'User authentication and authorization',
      'Message persistence',
      'Typing indicators',
      'Online/offline status',
      'Responsive design'
    ],
    skills: ['React', 'Node.js', 'WebSocket', 'MongoDB', 'TypeScript'],
    deadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-demo',
    organizationName: 'TechCorp Inc.',
    status: 'active',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-2',
    title: 'AI-Powered Code Review Tool',
    description: 'Develop an AI-powered tool that automatically reviews code for bugs, security vulnerabilities, and best practices. Integrate with GitHub API.',
    difficulty: 'Expert',
    type: 'AI/ML Development',
    prize: '$10,000',
    participants: 156,
    daysLeft: 12,
    requirements: [
      'GitHub API integration',
      'AI/ML model for code analysis',
      'Security vulnerability detection',
      'Code quality metrics',
      'Automated PR comments',
      'Dashboard for insights'
    ],
    skills: ['Python', 'Machine Learning', 'GitHub API', 'NLP', 'FastAPI'],
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-demo-2',
    organizationName: 'DevTools Labs',
    status: 'active',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-3',
    title: 'Mobile Fitness Tracker App',
    description: 'Create a cross-platform mobile app for fitness tracking with workout plans, calorie counting, and progress visualization.',
    difficulty: 'Intermediate',
    type: 'Mobile Development',
    prize: '$3,000',
    participants: 489,
    daysLeft: 15,
    requirements: [
      'Cross-platform mobile app (iOS & Android)',
      'Workout tracking and logging',
      'Calorie counter with food database',
      'Progress charts and analytics',
      'Social sharing features',
      'Push notifications'
    ],
    skills: ['React Native', 'Firebase', 'Redux', 'Chart.js', 'REST API'],
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-demo-3',
    organizationName: 'HealthTech Solutions',
    status: 'active',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-4',
    title: 'Blockchain-Based Supply Chain Tracker',
    description: 'Build a decentralized supply chain tracking system using blockchain technology. Track products from manufacturer to consumer.',
    difficulty: 'Expert',
    type: 'Blockchain Development',
    prize: '$8,000',
    participants: 203,
    daysLeft: 20,
    requirements: [
      'Smart contracts for tracking',
      'Web3 integration',
      'QR code scanning',
      'Product authenticity verification',
      'Multi-stakeholder dashboard',
      'Transaction history'
    ],
    skills: ['Solidity', 'Ethereum', 'Web3.js', 'React', 'IPFS'],
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-demo-4',
    organizationName: 'BlockChain Ventures',
    status: 'active',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'challenge-5',
    title: 'E-Commerce Recommendation Engine',
    description: 'Design and implement a machine learning-based product recommendation system for e-commerce platforms.',
    difficulty: 'Advanced',
    type: 'Data Science',
    prize: '$6,000',
    participants: 267,
    daysLeft: 10,
    requirements: [
      'Collaborative filtering algorithm',
      'Content-based recommendations',
      'Real-time personalization',
      'A/B testing framework',
      'Performance metrics dashboard',
      'API for integration'
    ],
    skills: ['Python', 'TensorFlow', 'Pandas', 'SQL', 'Docker'],
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-demo-5',
    organizationName: 'E-Shop Analytics',
    status: 'active',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
