// Comprehensive mock data for all features

export const mockJobs = [
  {
    id: 'job-1',
    title: 'Senior Full Stack Developer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salaryRange: '$140k - $180k',
    description: 'We are looking for an experienced Full Stack Developer to join our growing team.',
    requirements: ['5+ years experience', 'React, Node.js', 'TypeScript', 'AWS'],
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'AWS', 'MongoDB'],
    niceToHaveSkills: ['Docker', 'Kubernetes', 'GraphQL'],
    status: 'active',
    organizationId: 'org-1',
    organizationName: 'TechCorp Inc.',
    postedBy: 'John Smith',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    applicants: 45,
  },
  {
    id: 'job-2',
    title: 'Product Manager',
    department: 'Product',
    location: 'Remote',
    type: 'Full-time',
    salaryRange: '$120k - $160k',
    description: 'Lead product strategy and execution for our flagship products.',
    requirements: ['3+ years PM experience', 'Agile methodology', 'Data-driven'],
    requiredSkills: ['Product Strategy', 'Agile', 'Analytics', 'User Research'],
    niceToHaveSkills: ['SQL', 'Figma', 'A/B Testing'],
    status: 'active',
    organizationId: 'org-2',
    organizationName: 'StartupXYZ',
    postedBy: 'Sarah Johnson',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applicants: 67,
  },
  {
    id: 'job-3',
    title: 'DevOps Engineer',
    department: 'Infrastructure',
    location: 'New York, NY',
    type: 'Full-time',
    salaryRange: '$130k - $170k',
    description: 'Build and maintain our cloud infrastructure and CI/CD pipelines.',
    requirements: ['4+ years DevOps', 'AWS/GCP', 'Kubernetes', 'Terraform'],
    requiredSkills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD'],
    niceToHaveSkills: ['Python', 'Ansible', 'Monitoring'],
    status: 'active',
    organizationId: 'org-3',
    organizationName: 'CloudTech Solutions',
    postedBy: 'Mike Chen',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    applicants: 32,
  },
  {
    id: 'job-4',
    title: 'UX/UI Designer',
    department: 'Design',
    location: 'Austin, TX',
    type: 'Full-time',
    salaryRange: '$90k - $130k',
    description: 'Create beautiful and intuitive user experiences for our products.',
    requirements: ['3+ years design experience', 'Figma', 'User research'],
    requiredSkills: ['Figma', 'UI Design', 'UX Research', 'Prototyping'],
    niceToHaveSkills: ['Animation', 'Illustration', 'HTML/CSS'],
    status: 'active',
    organizationId: 'org-4',
    organizationName: 'DesignHub',
    postedBy: 'Emily Davis',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    applicants: 89,
  },
  {
    id: 'job-5',
    title: 'Data Scientist',
    department: 'Data',
    location: 'Seattle, WA',
    type: 'Full-time',
    salaryRange: '$150k - $200k',
    description: 'Build ML models and derive insights from large datasets.',
    requirements: ['PhD or 5+ years experience', 'Python', 'ML/AI', 'Statistics'],
    requiredSkills: ['Python', 'TensorFlow', 'SQL', 'Statistics', 'ML'],
    niceToHaveSkills: ['Spark', 'Scala', 'Deep Learning'],
    status: 'active',
    organizationId: 'org-5',
    organizationName: 'DataCorp',
    postedBy: 'Dr. James Wilson',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    applicants: 23,
  },
];

export const mockCourses = [
  {
    id: 'course-1',
    title: 'Advanced React Patterns',
    description: 'Master advanced React patterns including hooks, context, and performance optimization.',
    instructor: 'Kent C. Dodds',
    duration: '8 hours',
    level: 'Advanced',
    enrollments: 1234,
    rating: 4.8,
    thumbnail: 'https://api.dicebear.com/7.x/shapes/svg?seed=react',
    skills: ['React', 'JavaScript', 'Performance'],
    organizationId: 'org-1',
  },
  {
    id: 'course-2',
    title: 'System Design Fundamentals',
    description: 'Learn how to design scalable systems for tech interviews and real-world applications.',
    instructor: 'Alex Xu',
    duration: '12 hours',
    level: 'Intermediate',
    enrollments: 2156,
    rating: 4.9,
    thumbnail: 'https://api.dicebear.com/7.x/shapes/svg?seed=system',
    skills: ['System Design', 'Architecture', 'Scalability'],
    organizationId: 'org-2',
  },
  {
    id: 'course-3',
    title: 'Machine Learning A-Z',
    description: 'Complete machine learning course from basics to advanced topics.',
    instructor: 'Andrew Ng',
    duration: '40 hours',
    level: 'Beginner',
    enrollments: 5432,
    rating: 4.7,
    thumbnail: 'https://api.dicebear.com/7.x/shapes/svg?seed=ml',
    skills: ['Python', 'ML', 'Data Science'],
    organizationId: 'org-3',
  },
];

export const mockApplications = [
  {
    id: 'app-1',
    jobId: 'job-1',
    jobTitle: 'Senior Full Stack Developer',
    candidateId: 'candidate-1',
    candidateName: 'Alice Johnson',
    candidateEmail: 'alice@example.com',
    status: 'under_review',
    stage: 'technical_interview',
    appliedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-1',
    notes: 'Strong technical background',
    matchScore: 92,
  },
  {
    id: 'app-2',
    jobId: 'job-2',
    jobTitle: 'Product Manager',
    candidateId: 'candidate-2',
    candidateName: 'Bob Smith',
    candidateEmail: 'bob@example.com',
    status: 'shortlisted',
    stage: 'phone_screen',
    appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-2',
    notes: 'Great product sense',
    matchScore: 88,
  },
  {
    id: 'app-3',
    jobId: 'job-3',
    jobTitle: 'DevOps Engineer',
    candidateId: 'candidate-3',
    candidateName: 'Carol White',
    candidateEmail: 'carol@example.com',
    status: 'interview_scheduled',
    stage: 'final_interview',
    appliedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-3',
    notes: 'Excellent AWS experience',
    matchScore: 95,
  },
];

export const mockInterviews = [
  {
    id: 'interview-1',
    applicationId: 'app-1',
    candidateId: 'candidate-1',
    candidateName: 'Alice Johnson',
    candidateEmail: 'alice@example.com',
    jobTitle: 'Senior Full Stack Developer',
    scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    duration: 60,
    type: 'technical',
    status: 'scheduled',
    interviewerName: 'John Smith',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    organizationId: 'org-1',
  },
  {
    id: 'interview-2',
    applicationId: 'app-2',
    candidateId: 'candidate-2',
    candidateName: 'Bob Smith',
    candidateEmail: 'bob@example.com',
    jobTitle: 'Product Manager',
    scheduledAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    duration: 45,
    type: 'behavioral',
    status: 'scheduled',
    interviewerName: 'Sarah Johnson',
    meetingLink: 'https://zoom.us/j/123456789',
    organizationId: 'org-2',
  },
];

export const mockCandidates = [
  {
    id: 'candidate-1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    currentRole: 'Senior Software Engineer',
    experience: '7 years',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'MongoDB'],
    bio: 'Passionate full-stack developer with 7 years of experience building scalable web applications.',
    resumeURL: 'https://example.com/resume.pdf',
    linkedIn: 'linkedin.com/in/alicejohnson',
    github: 'github.com/alicejohnson',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
  },
  {
    id: 'candidate-2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    phone: '+1 (555) 234-5678',
    location: 'New York, NY',
    currentRole: 'Product Manager',
    experience: '5 years',
    skills: ['Product Strategy', 'Agile', 'Analytics', 'User Research'],
    bio: 'Data-driven product manager with a track record of launching successful products.',
    resumeURL: 'https://example.com/resume2.pdf',
    linkedIn: 'linkedin.com/in/bobsmith',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
  },
];

export const mockAnalytics = {
  totalApplications: 234,
  activeJobs: 12,
  interviewsScheduled: 18,
  offersExtended: 5,
  applicationTrend: [
    { month: 'Jan', applications: 45, interviews: 12, offers: 2 },
    { month: 'Feb', applications: 62, interviews: 18, offers: 3 },
    { month: 'Mar', applications: 78, interviews: 24, offers: 5 },
    { month: 'Apr', applications: 89, interviews: 28, offers: 6 },
    { month: 'May', applications: 95, interviews: 32, offers: 7 },
    { month: 'Jun', applications: 112, interviews: 38, offers: 9 },
  ],
  topSkills: [
    { skill: 'React', count: 89 },
    { skill: 'Python', count: 76 },
    { skill: 'Node.js', count: 65 },
    { skill: 'AWS', count: 54 },
    { skill: 'TypeScript', count: 48 },
  ],
};
